### ISSUE TITLE
Proba de issue_template 1

### ISSUE THREAD

**Issue by ferru11** [ferru11/Product-testing#16]
# US
### Developer Tasks
- [ ] **Code is produced**
- [ ] **Code has been reviewed**

### Approval Requirements
- [ ] **QA approval** - *@itmaryna*
- [ ] **Producer approval** - *@AlbertPedret*

---------------------------------------------------------------------------------------------------------
### Notes
- **[GDD](url)**
- **[Assets](url)**

## Tasks
- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

# BUG
## TITLE: 
Scene. Object. Problem

## DESCRIPTION:
- Device:
- OS: 
- App Version:
- Environment:
- Reproducibility: (at will, occasionally, almost never)
- Steps to reproduce: 
- Expected result:
- Actual result:
- Additional information: (screenshots, extra descriptions, etc.)
